### ISSUE TITLE
Bug in "math-python" environment

### ISSUE THREAD

**Issue by harmonbhasin** [PrimeIntellect-ai/verifiers#393]
I tried running `uv run vf-eval math-python` and got the following error:

```
❯ uv run vf-eval math-python
2025-09-30 12:54:25 - verifiers.scripts.eval - WARNING - No local endpoint registry found at ./configs/endpoints.py. Please specify the model name (-m), API host base URL (-b), and API key variable name (-k). Error details: endpoints.py not found at configs/endpoints.py
2025-09-30 12:54:25 - verifiers.utils.env_utils - INFO - Loading environment: math-python
2025-09-30 12:54:25 - verifiers.utils.env_utils - INFO - Using default args: dataset_name='math', num_train_examples=-1, dataset_split='train'
2025-09-30 12:54:30 - verifiers.utils.env_utils - ERROR - Failed to load environment math-python with args {}: module 'verifiers' has no attribute 'PythonEnv'
Traceback (most recent call last):
  File "/workspace/verifier-demo/.venv/lib/python3.11/site-packages/verifiers/__init__.py", line 109, in __getattr__
    module, attr = _LAZY_IMPORTS[name].split(":")
                   ~~~~~~~~~~~~~^^^^^^
KeyError: 'PythonEnv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/verifier-demo/.venv/lib/python3.11/site-packages/verifiers/utils/env_utils.py", line 72, in load_environment
    env_instance: Environment = env_load_func(**env_args)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/verifier-demo/.venv/lib/python3.11/site-packages/math_python.py", line 18, in load_environment
    vf_env = vf.PythonEnv(
             ^^^^^^^^^^^^
  File "/workspace/verifier-demo/.venv/lib/python3.11/site-packages/verifiers/__init__.py", line 112, in __getattr__
    raise AttributeError(f"module 'verifiers' has no attribute '{name}'")
AttributeError: module 'verifiers' has no attribute 'PythonEnv'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/verifier-demo/.venv/bin/vf-eval", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/workspace/verifier-demo/.venv/lib/python3.11/site-packages/verifiers/scripts/eval.py", line 333, in main
    eval_environment(
  File "/workspace/verifier-demo/.venv/lib/python3.11/site-packages/verifiers/scripts/eval.py", line 97, in eval_environment
    vf_env = vf.load_environment(env_id=env, **env_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/verifier-demo/.venv/lib/python3.11/site-packages/verifiers/utils/env_utils.py", line 89, in load_environment
    raise RuntimeError(f"Failed to load environment '{env_id}': {str(e)}") from e
RuntimeError: Failed to load environment 'math-python': module 'verifiers' has no attribute 'PythonEnv'

```

I got no such error when downloading and running the same command with gsm8k.

**Comment by anakin87** [comment]
How are you installing the environment?

My impression is that we are in a middle-ground situation: the env has been changed in https://github.com/PrimeIntellect-ai/verifiers/pull/384, so if you install it using `uv run vf-install math-python --from-repo`, you'll get this newer version.

But that version is not compatible with the latest stable release of verifiers (0.1.4).

Until 0.1.5 is released, I recommend installing verifiers from main: `uv add verifiers@git+https://github.com/PrimeIntellect-ai/verifiers.git`. (Alternatively, you could use the previous version of the environment together with 0.1.4.)

**Comment by willccbb** [comment]
should work with the 0.1.5.dev1 version! will bump requirements on the Environments Hub
