### ISSUE TITLE
Env server fails to start on Windows: ZMQ ipc:// transport is unsupported

### ISSUE THREAD

**Issue by martian56** [PrimeIntellect-ai/verifiers#2030]
### What happens

Running an evaluation on native Windows (`prime eval run ...`, which spins up the
verifiers env server) fails before a single rollout runs. The env-server subprocess
can't bind its internal ZMQ sockets, and the client receive loop errors out too.

Two errors fire:

1. Client receive loop:
   > Proactor event loop does not implement add_reader family of methods required for
   > zmq. zmq will work with proactor if tornado >= 6.1 can be found. Use
   > `asyncio.set_event_loop_policy(WindowsSelectorEventLoopPolicy())` or install
   > 'tornado>=6.1' to avoid this error.

2. Env server (fatal):
   > zmq.error.ZMQError: Protocol not supported (addr='ipc:///tmp/vf-...-responses')

### Root cause

`verifiers/utils/serve_utils.py`:

```python
def make_ipc_address(session_id, name):
    return f"ipc:///tmp/vf-{session_id}-{name.replace('/', '--')}"
```

The router↔worker sockets use ZMQ `ipc://` with a hardcoded `/tmp` path. `ipc://` is
Unix-domain-socket only and isn't supported on Windows, so `EnvRouter.__init__` fails at
`bind()`. There's no tcp fallback or override. Installing `tornado` only silences the
first Proactor error; the `ipc://` bind still fails regardless of the event loop.

### Impact

Anything that starts the env server — `prime eval run`, `prime gepa`, local `prime rl` —
cannot run on native Windows. Env authoring, `env install`, and `env push` are unaffected.

### Environment

- OS: Windows 11
- Python 3.12
- verifiers 0.2.0 (same code on `main`)

### Steps to reproduce

```
prime env init demo        # any trivial SingleTurnEnv
prime env install demo
prime eval run demo -m openai/gpt-4o-mini -p openrouter -n 1 -c 1 --disable-tui
```

Traceback (paths trimmed):

```
verifiers.serve.client.env_client.ZMQEnvClient - ERROR - Unexpected error in receive loop
for env server demo (tcp://127.0.0.1:PORT) (Proactor event loop does not implement
add_reader family of methods required for zmq. zmq will work with proactor if tornado
>= 6.1 can be found. Use `asyncio.set_event_loop_policy(WindowsSelectorEventLoopPolicy())`
or install 'tornado>=6.1' to avoid this error.)
Traceback (most recent call last):
  File ".../zmq/asyncio.py", line 51, in _get_selector_windows
    from tornado.platform.asyncio import AddThreadSelectorEventLoop
ModuleNotFoundError: No module named 'tornado'

During handling of the above exception, another exception occurred:

  File ".../verifiers/serve/client/zmq_env_client.py", line 198, in receive_loop
    msg = await self.socket.recv_multipart()
  ...
RuntimeError: Proactor event loop does not implement add_reader family of methods required
for zmq. ...

Process SpawnProcess-1:
Traceback (most recent call last):
  File ".../verifiers/serve/server/env_server.py", line 145, in run_server
    server = cls(*args, **kwargs)
  File ".../verifiers/serve/server/env_router.py", line 134, in __init__
    self.response_pull.bind(self.response_address)
  File ".../zmq/sugar/socket.py", line 320, in bind
    super().bind(addr)
  ...
zmq.error.ZMQError: Protocol not supported (addr='ipc:///tmp/vf-...-responses')
```

### Workaround

Run under WSL/Linux, where `ipc:///tmp` works.

**Comment by arthi-arumugam-git** [comment]
Opened #2176 for the fatal half of this. Your root cause was right: `ipc://` cannot bind on Windows and `make_ipc_address` hardcodes it.

Reproduced natively on Windows 11, pyzmq 27.1.0 / libzmq 4.3.5, with the same error text you got:

```
zmq.has("ipc") = False
main         ipc:///tmp/vf-abc123-responses  ->  ZMQError: Protocol not supported
this branch  tcp://127.0.0.1:50465           ->  binds
```

The PR gates on `zmq.has("ipc")` rather than the platform, since that is the capability the transport choice actually depends on and it also catches a libzmq built without ipc on any OS.

Two things turned up while fixing it that are not in the report. `/tmp` being hardcoded is a second, separate bug: it ignores `tempfile.gettempdir()` and breaks anywhere `/tmp` is not writable, regardless of OS. And `EnvRouter` unlinks every entry of `ipc_paths` on shutdown, built by stripping the `ipc://` prefix, so a tcp address would have been handed to `os.unlink`. Fixing only the transport would have traded your startup crash for a shutdown one.

I left your first error out on purpose. pyzmq works under Proactor once `tornado>=6.1` is present, and setting a global asyncio event loop policy from inside a library affects embedders, so that felt like a CLI-entry-point call for a maintainer rather than something to bake in. Happy to add it if they want it there.

One thing I could not do: I do not have a provider key, so I could not run `prime eval run` end to end. If you still have your setup, that would be a useful confirmation on top of the unit tests.

**Comment by xeophon** [comment]
hey @martian56! we use a bunch of unix-only functionality across v1. fixing `ipc://` only wouldn't cut it. we recommend using WSL
